config/routes.rb
Rails.application.routes.draw do
  resources :visa_details
  resources :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/duration.rb
class Duration < ApplicationRecord
  has_and_belongs_to_many :visa_details
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :visa_detail
  has_and_belongs_to_many :relationships
  validates :family_name, :given_names, :gender, :date_of_birth, :passport_number, :country_of_passport, :passport_nationality,
      :date_of_issue, :date_of_expired, :issueing_authority, presence: true,  unless: Proc.new { |record| record.visa_detail.is_more_occasion }
end

app/models/visa_detail.rb
class VisaDetail < ApplicationRecord
  has_and_belongs_to_many :durations
  has_one   :user
  accepts_nested_attributes_for :user

  validates :used_pen, :detailed_description, :name_of_city, :name_of_state, :name_of_country, presence: true

  validates :visiting_from, :visiting_to, presence: true, if: Proc.new { |vd| vd.outside_country}
  validates :date_of_extend, presence: true, if: Proc.new { |vd| vd.inside_country}

  validates :types_of_occasion, presence: true, if: Proc.new { |vd| vd.is_more_occasion}

  mount_uploader :image, ImageUploader

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/visa_details_controller.rb
class VisaDetailsController < ApplicationController
  before_action :set_visa_detail, only: %i[ show edit update destroy ]

  # GET /visa_details or /visa_details.json
  def index
    @visa_details = VisaDetail.all
  end

  # GET /visa_details/1 or /visa_details/1.json
  def show
  end

  # GET /visa_details/new
  def new
    @visa_detail = VisaDetail.new
    @visa_detail.build_user
  end

  # GET /visa_details/1/edit
  def edit
  end

  # POST /visa_details or /visa_details.json
  def create
    @visa_detail = VisaDetail.new(visa_detail_params)
    #binding.pry
    respond_to do |format|
      if @visa_detail.save
        if  params[:visa_detail].present? && params[:visa_detail][:duration_ids].present?
          durations = Duration.find params[:visa_detail][:duration_ids]
          @visa_detail.durations = durations
        end

        if params[:user].present? && params[:user].fetch(:relationship_ids).present?
          @relationships = Relationship.where(:id => params[:user][:relationship_ids])
          @visa_detail.user.relationships << @relationships
        end
        format.html { redirect_to @visa_detail, notice: "Visa detail was successfully created." }
        format.json { render :show, status: :created, location: @visa_detail }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visa_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visa_details/1 or /visa_details/1.json
  def update
    respond_to do |format|
      if @visa_detail.update(visa_detail_params)
        format.html { redirect_to @visa_detail, notice: "Visa detail was successfully updated." }
        format.json { render :show, status: :ok, location: @visa_detail }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visa_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visa_details/1 or /visa_details/1.json
  def destroy
    @visa_detail.destroy
    respond_to do |format|
      format.html { redirect_to visa_details_url, notice: "Visa detail was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visa_detail
      @visa_detail = VisaDetail.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visa_detail_params
      params.require(:visa_detail).permit(:used_pen,:outside_country,
                                          :inside_country, :visiting_from, :visiting_to, :is_more_occasion, :types_of_occasion,
                                          :date_of_extend, :detailed_description, :image, :name_of_city, :name_of_state, :name_of_country, duration_ids: [:id],
                                          user_attributes: [:family_name, :given_names, :date_of_birth, :passport_number, :country_of_passport, :passport_nationality,
                                                  :date_of_issue, :date_of_expired, :ssueing_authority])

    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/visa_details_helper.rb
module VisaDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LotVueApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/visa_details/edit.html.erb
<%= render 'form', visa_detail: @visa_detail %>

app/views/visa_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visa Details</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visa_details.each do |visa_detail| %>
      <tr>
        <td><%= visa_detail.try(:user).try(:family_name) %></td>
        <td><%= visa_detail.try(:user).try(:gender) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visa Detail', new_visa_detail_path %>

app/views/visa_details/new.html.erb
<%= render 'form', visa_detail: @visa_detail %>

app/views/visa_details/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_visa_detail_path(@visa_detail) %> |
<%= link_to 'Back', visa_details_path %>